version: 2

jobs:
    build:
        docker:
            - image: ubuntu:20.04
            - image: postgis/postgis:14-master
              environment:
                  POSTGRES_HOST_AUTH_METHOD: trust
            - image: memcached:1.6

        steps:
            - run:
                name: "Add ubuntu-toolchain"
                command: |
                  apt-get update -y \
                  && apt-get install -y build-essential git postgresql-client curl wget gnupg2 python3

            - checkout

            - run:
                name: "Install NodeJS"
                command: |
                  curl 'https://nodejs.org/dist/v19.0.0/node-v19.0.0-linux-x64.tar.gz' | tar -xzv \
                  && cp ./node-v19.0.0-linux-x64/bin/node /usr/bin/ \
                  && ./node-19.0.0-linux-x64/bin/npm install -g yarn \
                  && ./node-19.0.0-linux-x64/bin/npm install -g npm \
                  && echo "export PATH=$(yarn global bin):$PATH" >> $BASH_ENV \
                  yarn install

            - run:
                name: "Test"
                command: ./test
