name: Test API

on: [push]

jobs:



    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgis/postgis:12-master
                ports: ["5432:5432"]
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1
              with:
                node-version: '12.x'

            - name: Yarn Install
              run: yarn install --production=false
              working-directory: ./api/

            - name: Yarn Lint
              run: yarn lint
              working-directory: ./api/

            - name: Yarn Test
              run: yarn test
              working-directory: ./api/
