name: Test API

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1
              with:
                node-version: '12.x'

            - name: Yarn Install
              run: cd ./api && yarn install

            - name: Yarn Lint
              run: cd ./api && yarn lint

            - name: Yarn Test
              run: cd ./api  && yarn test
